config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :satisfactions

  root 'welcome#index'

end

app/models/satisfaction.rb
class Satisfaction < ActiveRecord::Base
  validates :date,:name,:category,:score, presence: true
  validates :score, numericality: { only_integer: true, less_than_or_equal_to: 10, greater_than: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/satisfactions_controller.rb
class SatisfactionsController < ApplicationController
  def index
    @satisfactions = Satisfaction.all
  end

  def show
    @satisfaction = Satisfaction.find(params[:id])
  end

  def new
    @satisfaction = Satisfaction.new
  end

  def create
    @satisfaction = Satisfaction.new(satisfaction_params)

    if @satisfaction.save
      redirect_to @satisfaction
    else
      render 'new'
    end
  end

  private
    def satisfaction_params
      params.require(:satisfaction).permit(:date, :name, :category, :score)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/satisfactions_helper.rb
module SatisfactionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TeamDashBoard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/satisfactions/_form.html.erb
<%= form_for @satisfaction do |f| %>

  <% if @satisfaction.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@satisfaction.errors.count, "error") %> prohibited
        this entry from being saved:
      </h2>
      <ul>
        <% @satisfaction.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :date %><br>
    <%= f.date_field :date %>
  </p>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </p>

  <p>
    <%= f.label :score %><br>
    <%= f.text_field :score %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/satisfactions/index.html.erb
<style>
table {
    width:80%;
}
table, th, td {
    border: 1px solid black;
    border-collapse: collapse;
}
th, td {
    padding: 5px;
    text-align: left;
}
table#t01 tr:nth-child(even) {
    background-color: #eee;
}
table#t01 tr:nth-child(odd) {
   background-color:#fff;
}
table#t01 th	{
    background-color: black;
    color: white;
}
</style>

<h1>Member satisfactions Index!</h1>

<%= link_to 'New satisfaction', new_satisfaction_path %>

<table id="t01">
  <tr>
    <th>ID</th>
    <th>Date</th>
    <th>Name</th>
    <th>Category</th>
    <th>Score</th>
  </tr>
<% @satisfactions.each do |satisfaction| %>
  <tr>
    <td><%= satisfaction.id %></td>
    <td><%= satisfaction.name %></td>
    <td><%= satisfaction.date %></td>
    <td><%= satisfaction.category %></td>
    <td><%= satisfaction.score %></td>
  </tr>
<% end %>
</table>

app/views/satisfactions/new.html.erb
<h1>Member satisfactions!</h1>
<%= render 'form' %>

app/views/satisfactions/show.html.erb
<p>
  <strong>Date:</strong>
  <%= @satisfaction.date %>
</p>

<p>
  <strong>Name:</strong>
  <%= @satisfaction.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @satisfaction.category %>
</p>

<p>
  <strong>Score:</strong>
  <%= @satisfaction.score %>
</p>

<%= link_to 'Back', satisfactions_path %>

app/views/welcome/index.html.erb
<h1>Liangzhu Dashboard!</h1>
<%= link_to 'Member satisfaction', controller: 'satisfactions' %>